# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-18 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allapp', '0003_auto_20190218_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_name', models.CharField(max_length=1500, verbose_name='Contract Name')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Contract Type',
                'verbose_name_plural': 'Contract Types',
            },
        ),
        migrations.CreateModel(
            name='ExperienceLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_name', models.CharField(max_length=1500, verbose_name='Experience Name')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Experience Level',
                'verbose_name_plural': 'Experience Levels',
            },
        ),
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_name', models.CharField(max_length=1500, verbose_name='Experience Name')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Experience Level',
                'verbose_name_plural': 'Experience Levels',
            },
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=1500, verbose_name='Job Type name')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'JobType',
                'verbose_name_plural': 'JobTypes',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=1500, verbose_name='City Name')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'City or Country',
                'verbose_name_plural': 'Cities or Countries',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(max_length=1500, verbose_name='Sector name')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
            },
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Vacancy', 'verbose_name_plural': 'Vacancies'},
        ),
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
