# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-18 14:34
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allapp', '0004_auto_20190218_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='email',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='job',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiry Date'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_contract_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracttype', to='allapp.ContractType', verbose_name='Contract Type'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_experience_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiencelevel', to='allapp.ExperienceLevel', verbose_name='Experience Level'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_hours',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='allapp.Hours', verbose_name='Hours'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='allapp.Location', verbose_name='Job location'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sector', to='allapp.Sector', verbose_name='Job sector'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobtype', to='allapp.JobType', verbose_name='Job Type'),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='job',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='About job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='content_az',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='About job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='About job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=1500, verbose_name='Job name'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title_az',
            field=models.CharField(max_length=1500, null=True, verbose_name='Job name'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title_en',
            field=models.CharField(max_length=1500, null=True, verbose_name='Job name'),
        ),
    ]
