# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-18 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allapp', '0005_auto_20190218_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_location',
        ),
        migrations.AddField(
            model_name='job',
            name='job_location',
            field=models.ManyToManyField(null=True, related_name='location', to='allapp.Location', verbose_name='Job location'),
        ),
    ]
