# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-18 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allapp', '0007_auto_20190218_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_location',
        ),
        migrations.AddField(
            model_name='job',
            name='job_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='allapp.Location', verbose_name='Job location'),
        ),
    ]
