# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-18 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allapp', '0008_auto_20190218_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencelevel',
            name='experience_name_az',
            field=models.CharField(max_length=1500, null=True, verbose_name='Experience Name'),
        ),
        migrations.AddField(
            model_name='experiencelevel',
            name='experience_name_en',
            field=models.CharField(max_length=1500, null=True, verbose_name='Experience Name'),
        ),
    ]
