# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-18 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allapp', '0009_auto_20190218_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtype',
            name='job_name_az',
            field=models.CharField(max_length=1500, null=True, verbose_name='Job Type name'),
        ),
        migrations.AddField(
            model_name='jobtype',
            name='job_name_en',
            field=models.CharField(max_length=1500, null=True, verbose_name='Job Type name'),
        ),
        migrations.AddField(
            model_name='location',
            name='city_name_az',
            field=models.CharField(max_length=1500, null=True, verbose_name='City Name'),
        ),
        migrations.AddField(
            model_name='location',
            name='city_name_en',
            field=models.CharField(max_length=1500, null=True, verbose_name='City Name'),
        ),
        migrations.AddField(
            model_name='sector',
            name='sector_name_az',
            field=models.CharField(max_length=1500, null=True, verbose_name='Sector name'),
        ),
        migrations.AddField(
            model_name='sector',
            name='sector_name_en',
            field=models.CharField(max_length=1500, null=True, verbose_name='Sector name'),
        ),
    ]
