# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-18 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allapp', '0013_auto_20190218_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='CvSend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1500, verbose_name='Ad')),
                ('surname', models.CharField(max_length=1500, verbose_name='Soyad')),
                ('email', models.CharField(max_length=1500, verbose_name='Email')),
                ('cv', models.FileField(upload_to='', verbose_name='Cv')),
                ('cover_letter', models.FileField(upload_to='', verbose_name='Məktub')),
            ],
        ),
    ]
