# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-18 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allapp', '0016_auto_20190218_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvsend',
            name='apply_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='allapp.Job', verbose_name='Job'),
        ),
    ]
