# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-18 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allapp', '0021_auto_20190219_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvsend',
            name='apply_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='allapp.Job', verbose_name='Job'),
        ),
    ]
