# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-18 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allapp', '0023_auto_20190219_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvsend',
            name='apply_name',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Job name'),
        ),
        migrations.AlterField(
            model_name='cvsend',
            name='apply_for',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Job slug'),
        ),
    ]
