# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-19 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allapp', '0024_auto_20190219_0127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cvsend',
            options={'ordering': ['-id'], 'verbose_name': 'CV', 'verbose_name_plural': 'ALL CV'},
        ),
        migrations.AlterField(
            model_name='cvsend',
            name='apply_for',
            field=models.CharField(blank=True, editable=False, max_length=1500, null=True, verbose_name='Job slug'),
        ),
        migrations.AlterField(
            model_name='cvsend',
            name='apply_name',
            field=models.CharField(blank=True, editable=False, max_length=1500, null=True, verbose_name='Job name'),
        ),
    ]
