# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-19 17:38
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allapp', '0025_auto_20190219_0447'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_title', models.CharField(max_length=1500, verbose_name='Title')),
                ('a_title_az', models.CharField(max_length=1500, null=True, verbose_name='Title')),
                ('a_title_en', models.CharField(max_length=1500, null=True, verbose_name='Title')),
                ('a_content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('a_content_az', ckeditor.fields.RichTextField(null=True, verbose_name='Content')),
                ('a_content_en', ckeditor.fields.RichTextField(null=True, verbose_name='Content')),
            ],
            options={
                'verbose_name': 'About us',
                'verbose_name_plural': 'About us',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telphone', models.CharField(max_length=1500, verbose_name='Telphone')),
                ('location', models.CharField(max_length=1500, verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Contact us',
                'verbose_name_plural': 'Contact us',
            },
        ),
    ]
