# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-08 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allapp', '0026_aboutus_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='draft',
            field=models.BooleanField(default=True, verbose_name='Public?'),
        ),
    ]
