# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-08-09 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allapp', '0028_remove_cvsend_surname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(max_length=200, verbose_name='Industry Name')),
            ],
            options={
                'verbose_name': 'Industry',
                'verbose_name_plural': 'Industry',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='job_industry_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='industry', to='allapp.Industry', verbose_name='Industry'),
        ),
    ]
